# 端口号
server:
  port: 9000
#数据库连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://120.77.28.123:3306/oa_project?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/oa-project?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
#    password: Zwy172839456,
    password: 123456
  #应用名称
  application:
    name: oa-server
  #静态资源配置
#  mvc:
#    static-path-pattern: /static/**
#  web:
#    resources:
#      static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources,file:static
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  jackson:
    time-zone: GMT+8

#mybatos-Plus配置
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml
